In [43]:
import numpy as np

# Multidimensional Arrays 
twoD = np.arange(9).reshape(3, 3)
oneD = np.array([1.2, 3.5, 5.1])
threeD = np.arange(27).reshape(3, 3, 3)
print("Two dimesnional", twoD)
print("One dimensional", oneD)
print("Three dimensional ", threeD)
threeD

Two dimesnional [[0 1 2]
 [3 4 5]
 [6 7 8]]
One dimensional [1.2 3.5 5.1]
Three dimensional  [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [19]:
twoD.shape

(3, 3)

In [20]:
oneD.shape

(3,)

In [21]:
twoD.ndim

2

In [40]:
threeD.ndim

3

In [22]:
oneD.ndim

1

In [13]:
twoD.itemsize

8

In [23]:
oneD.itemsize

8

In [25]:
twoD.size

9

In [26]:
oneD.size

3

In [16]:
type(twoD)

numpy.ndarray

In [24]:
type(oneD)

numpy.ndarray

In [27]:
twoD[:2, :2]

array([[0, 1],
       [3, 4]])

In [28]:
twoD.mean()

4.0